### ISSUE TITLE
Erro na execução do docker-composer

### ISSUE THREAD

**Issue by albuquerquefabio** [jersobh/php-boleto-cnab#10]
Olá pessoal estou com esse problema aqui:
ao executar `docker-compose build`
aparece esse erro na etapa 24/31

`Step 24/31 : RUN composer install
 ---> Running in 0a28ed0c0bf0
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer could not find a composer.json file in /www/api
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
ERROR: Service 'pbc-front' failed to build: The command '/bin/sh -c composer install' returned a non-zero code: 1`

Já fiz de tudo (eu acho), ja testei no mac os e o linux. Até agora nada funcionou. 
Vlw!

**Comment by jersobh** [comment]
Ele tá lá, mano. https://github.com/jersobh/php-boleto-cnab/blob/master/www/api/composer.json
Dá uma conferida no seu e qualquer coisa tenta criar manualmente o composer.json dentro de www/api, usando esse conteúdo do link acima.

**Comment by jersobh** [comment]
Corrigi o problema! Era um bug do composer, deve funcionar agora.

**Comment by albuquerquefabio** [comment]
BLZ! Vou testar e mando o feedback.
Na verdade eu consegui executar dando o comando `composer update` e depois`composer install` direto na pasta que estava o composer.json e coloquei para executar em um servidor apache.

**Comment by jersobh** [comment]
Boa =]
