### ISSUE TITLE
Erro na instalação

### ISSUE THREAD

**Issue by belmirofss** [jersobh/php-boleto-cnab#11]
Olá, tudo bem rapaziada? To precisando de uma ajudinha de vocês. Estou precisando emitir boletos com o arquivo de remessa e achei esse projeto perfeito, entretanto estou com esse problema e não sei praticamente nada de Docker (e bem pouco do próprio PHP). 

Apenas executei o comando docker-compose build e recebi esse erro:

Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer could not find a composer.json file in /www/api
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
ERROR: Service 'pbc-front' failed to build: The command '/bin/sh -c composer install' returned a non-zero code: 1

Alguém pode me ajudar?

**Comment by jersobh** [comment]
Corrigi o problema! Era um bug do composer, deve funcionar agora.

**Comment by belmirofss** [comment]
> Corrigi o problema! Era um bug do composer, deve funcionar agora.

Muito obrigado! Agora consegui instalar, entretanto ao dar sudo docker-compose up recebo o seguinte erro: 

ERROR: for pbc-front  Cannot start service pbc-front: driver failed programming external connectivity on endpoint phpboletocnab_pbc-front_1 (8b230f9d5a2807db1dcb942e73f8baa78c6e10a14f81da03872562e694d72742): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by belmirofss** [comment]
> Corrigi o problema! Era um bug do composer, deve funcionar agora.

Muito obrigado! Instalou agora perfeitamente, entretanto tive um pequeno problema, quando dou o sudo docker-composer up, aparentemente ele fica rodando certo, essas foram as ultimas mensagens recebidas: 

pbc-mongodb_1  | 2019-02-05T12:02:17.165+0000 I CONTROL  [initandlisten] 
pbc-mongodb_1  | 2019-02-05T12:02:17.165+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
pbc-mongodb_1  | 2019-02-05T12:02:17.165+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
pbc-mongodb_1  | 2019-02-05T12:02:17.165+0000 I CONTROL  [initandlisten] 
pbc-mongodb_1  | 2019-02-05T12:02:18.055+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
pbc-mongodb_1  | 2019-02-05T12:02:18.282+0000 I NETWORK  [initandlisten] waiting for connections on port 27017

Mas ao acessar o localhost, recebo o seguinte erro:
Warning: require(/var/www/api/public/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/api/public/index.php on line 12

Fatal error: require(): Failed opening required '/var/www/api/public/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/api/public/index.php on line 12

Sabe o que posso fazer? 

Aproveitando já o espaço, percebi que é mapeado para a porta 80, gostaria de saber se existe um jeito simples e sem problemas para que eu possa alterar essa porta, pois na 80 brevemente estarei rodando o apache2.

**Comment by jersobh** [comment]
Alterei a porta padrão para 8080, pode testar por favor?

**Comment by belmirofss** [comment]
Posso sim, entretanto está ocorrendo esse erro que disse. 

Warning: require(/var/www/api/public/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/api/public/index.php on line 12

Fatal error: require(): Failed opening required '/var/www/api/public/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/api/public/index.php on line 12

Essa pasta vendor com o arquivo autoload.php não existe.

**Comment by jersobh** [comment]
Estranho, pq o composer deve instalar o autoload, conforme o autoload.json...

**Comment by jersobh** [comment]
Fiz mais um commit, mas não tenho certeza se vai resolver.

**Comment by belmirofss** [comment]
Não resolveu. Mesmo erro. Navegando pelos diretórios, realmente não existe a vendor/autoload.php.

**Comment by belmirofss** [comment]
O próprio caminho está estranho:

Fatal error: require(): Failed opening required '/var/www/api/public/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/api/public/index.php on line 12

Tem um ".." solto antes da /vendor. Mas de qualquer forma ela nem existe

**Comment by belmirofss** [comment]
Apenas uma observação, talvez seja boba de minha parte, essa mensagem aqui não pode estar interferindo? 

Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files


Aparece quando dá o docker-compose build, talvez não esteja conseguindo rodar o composer

**Comment by jersobh** [comment]
A ser implementado em #14
