### ISSUE TITLE
Problema ao executar docker-compose build

### ISSUE THREAD

**Issue by IgorMSampaio** [jersobh/php-boleto-cnab#12]
Bem, é simple quando vou executar o comando docker-compose build aparece esse erro o que eu estou errando?

> C:\Apache24\htdocs\php-boleto-cnab>docker-compose build
> pbc-mongodb uses an image, skipping
> Building pbc-front
> ERROR: Windows named pipe error: O sistema não pode encontrar o arquivo especificado. (code: 2)

**Comment by jersobh** [comment]
Provavelmente o autoload. Roda um composer install no projeto pra instalar as dependencias.

**Comment by jersobh** [comment]
Duplicate of #11
