### ISSUE TITLE
http://localhost:8080/ 

### ISSUE THREAD

**Issue by janiopimentel** [jersobh/php-boleto-cnab#16]
Instalei o Docker, rodei os comandos docker-compose build   e docker-compose up

Quando vou até o navegador, apresenta a seguinte mensagem:

Esta página não está funcionandoNenhum dado foi enviado por localhost
ERR_EMPTY_RESPONSE

Podem me ajudar?

**Comment by jersobh** [comment]
Precisa tbm rodar o composer pra instalar as libs do PHP.

>

**Comment by janiopimentel** [comment]
Ao rodar o COMPOSER, apresentou o seguinte problema:  

Problem 1
    - The requested package jersobh/php-boleto-cnab could not be found in any version, there may be a typo in the package name.

**Comment by janiopimentel** [comment]
Notei que o "composer install" deveria ser rodado dentre da pasta www\api\

Rodei e mesmo assim continua o mesmo problema inicial (não abre o localhost:8080)

**Comment by janiopimentel** [comment]
Alguém consegue me ajudar?

**Comment by williambh** [comment]
Caso algum outro serviço já esteja usando a porta, não vai funcionar mesmo.
É importante saber se os containers estão rodando. Use:

```docker ps ``` 

pra listar todos os containers ativos. 
Para mais comandos, veja https://docs.docker.com/engine/reference/commandline/docker/

**Comment by janiopimentel** [comment]
C:\xampp5\htdocs\sisfv\boleto>docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                NAMES
5681e78706b4        boleto_pbc-front    "/usr/bin/supervisord"   56 minutes ago      Up 56 minutes       0.0.0.0:443->443/tcp, 0.0.0.0:9000->9000/tcp, 0.0.0.0:8080->80/tcp   boleto_pbc-front_1
17a1917a4cfd        mongo               "docker-entrypoint.s…"   56 minutes ago      Up 56 minutes       0.0.0.0:27017->27017/tcp                                             boleto_pbc-mongodb_1

**Comment by jersobh** [comment]
@janiopimentel às vezes não é outro container, mas um serviço rodando aí. Não vejo sentido os 3 containers up e não abrir. Testa de uma maquina linux, pq windows nem é sistema operacional.

**Comment by janiopimentel** [comment]
Dois container....

**Comment by jersobh** [comment]
Dá um git pull aí e roda  
docker-compose up --force-recreate
Acabei de commitar um fix ad04b4d448e4fcc7a6d89d235fd445836f82dd38

**Comment by williambh** [comment]
> Dá um git pull aí e roda
> docker-compose up --force-recreate
> Acabei de commitar um fix [ad04b4d](https://github.com/jersobh/php-boleto-cnab/commit/ad04b4d448e4fcc7a6d89d235fd445836f82dd38)

Além desse BUG no Dockerfile, o Build no docker-compose está aparecendo duas vezes... não é necessário...

```
diff --git a/docker-compose.yml b/docker-compose.yml
index e24e88c..3a5bc0b 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -6,7 +6,7 @@ pbc-front:
     - "9000:9000"
   links:
     - pbc-mongodb:pbc-mongodb
-  build: ./
+      #  build: ./
   volumes:
     - ./www:/var/www
     - ./sites:/etc/nginx/conf.d
```

**Comment by jersobh** [comment]
Bem observado, valeu @williambh !

**Comment by janiopimentel** [comment]
Feito e mesmo assim:

Esta página não está funcionando
Nenhum dado foi enviado por localhost
ERR_EMPTY_RESPONSE

**Comment by jersobh** [comment]
@janiopimentel, você deve estar com algum cache. Da um prune nos volumes, imagens, etc. Seu problema agora acredito ser relacionado ao docker que à API.
