### ISSUE TITLE
Estou com um erro ao start o docker, poderia ajudar? 

### ISSUE THREAD

**Issue by RicardoFideles** [jersobh/php-boleto-cnab#3]
Quando eu starto o docker-compose up, estou recebendo o seguinte erro.

[100%] Building CXX object CMakeFiles/mongo.dir/src/decode.cpp.o
/tmp/mongofill-hhvm/src/decode.cpp: In function 'HPHP::ObjectData* HPHP::instanceNewObject(const HPHP::StaticString*, HPHP::Array)':
/tmp/mongofill-hhvm/src/decode.cpp:149:3: error: no matching function for call to 'HPHP::ExecutionContext::invokeFunc(HPHP::TypedValue*, const HPHP::Func*, HPHP::Array&, HPHP::ObjectData*&)'
   );
   ^
/tmp/mongofill-hhvm/src/decode.cpp:149:3: note: candidates are:
In file included from /tmp/mongofill-hhvm/src/decode.cpp:2:0:
/usr/include/hphp/runtime/base/execution-context.h:428:14: note: HPHP::TypedValue HPHP::ExecutionContext::invokeFunc(const HPHP::Func*, const HPHP::Variant&, HPHP::ObjectData*, HPHP::Class*, HPHP::VarEnv*, HPHP::StringData*, HPHP::ExecutionContext::InvokeFlags, bool)
   TypedValue invokeFunc(const Func* f,
              ^
/usr/include/hphp/runtime/base/execution-context.h:428:14: note:   no known conversion for argument 1 from 'HPHP::TypedValue*' to 'const HPHP::Func*'
In file included from /usr/include/hphp/runtime/base/execution-context.h:588:0,
                 from /tmp/mongofill-hhvm/src/decode.cpp:2:
/usr/include/hphp/runtime/base/execution-context-inl.h:189:19: note: HPHP::TypedValue HPHP::ExecutionContext::invokeFunc(const HPHP::CallCtx&, const HPHP::Variant&, HPHP::VarEnv*)
 inline TypedValue ExecutionContext::invokeFunc(
                   ^
/usr/include/hphp/runtime/base/execution-context-inl.h:189:19: note:   candidate expects 3 arguments, 4 provided
CMakeFiles/mongo.dir/build.make:100: recipe for target 'CMakeFiles/mongo.dir/src/decode.cpp.o' failed
make[2]: *** [CMakeFiles/mongo.dir/src/decode.cpp.o] Error 1
make[1]: *** [CMakeFiles/mongo.dir/all] Error 2
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/mongo.dir/all' failed
make: *** [all] Error 2
Makefile:117: recipe for target 'all' failed
ERROR: Service 'pbc-front' failed to build: The command '/bin/sh -c ./build.sh' returned a non-zero code: 2

**Comment by jersobh** [comment]
Olá! Está usando a branch dev? Ela possui o eloquent incluso. De qualquer forma, irei alterar o docker hoje para php7-fpm no lugar do HHVM. Então amanhã pode fazer o pull que irá funcionar. É um problema que também tive aqui com o hhvm. No entanto agora não consigo reproduzí-lo, pois voltou a compilar e funcionar corretamente.

**Comment by possebon** [comment]
@jersobh Eu fiz o pull hoje e deu o mesmo erro que foi descrito antes.

**Comment by jersobh** [comment]
Sim, infelizmente o repositorio que usei pra subir o hhvm no docker foi aparentemente abandonado e não funciona mais. Tenho que corrigir o docker, mas estou meio sem tempo.

**Comment by jersobh** [comment]
Pessoal, repositório atualizado. Criei uma função GET em /boleto/teste para testar.

**Comment by jersobh** [comment]
Tudo foi migrado para PHP 7, HHVM não é mais usado.
