### ISSUE TITLE
Como conectar o php 7.22 no sqlserver 2017 

### ISSUE THREAD

**Issue by W1ll14nC4rl0s** [jersobh/php-boleto-cnab#5]
Estou tendo dificuldade pra realizar a conexao com o banco de dados para emitir os boletos pois o driver da microsoft 4.3 so cobre ate a versao 7.1 do php alguma solução?

**Comment by jersobh** [comment]
Não sei se já resolveu, mas o sistema usa docker. E o banco de dados utilizado é MySQL.
