### ISSUE TITLE
Erro na instalação

### ISSUE THREAD

**Issue by leovicio** [jersobh/php-boleto-cnab#6]
Estou tentando instalar mas da esse erro!
WARNING: The following packages cannot be authenticated!
  hhvm
E: There are problems and -y was used without --force-yes
ERROR: Service 'pbc-front' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y hhvm php5-dev php5-cli php-pear php5-mongo' returned a non-zero code: 100

**Comment by jersobh** [comment]
Deve estar usando uma branch antiga. A branch mais recente usa php7, não hhvm.

**Comment by msbessa** [comment]
Estou com o mesmo problema acima... 
A imagem disponível do arquivo Dockerfile é com php5... e esta com erro na instalação!!!

**Comment by diego-miranda-ng** [comment]
Também estou com este problema e não estou conseguindo instalar o projeto.

**Comment by jersobh** [comment]
Podem verificar se o commit [#59](https://github.com/jersobh/php-boleto-cnab/commit/80b8d72c3fe4a5ad083bebeef3b27b07bffa07e5) resolve o problema?

**Comment by lukBarros** [comment]
@jersobh nao resolve estou no commit #59 e o problema persiste

**Comment by lukBarros** [comment]
php7ou 5?

**Comment by diego-miranda-ng** [comment]
Aqui o problema também persiste na instalação.

**Comment by jersobh** [comment]
Sim, qual o erro agora?
