### ISSUE TITLE
Rodar isso sem Docker

### ISSUE THREAD

**Issue by lukBarros** [jersobh/php-boleto-cnab#7]
Há instrunções básicas de como rodar isso fora do docker?

**Comment by jersobh** [comment]
No que diz respeito à API, tá tudo dentro de www. Só rodar um ambiente com php5 e mongodb.

**Comment by lukBarros** [comment]
Ok Qual nível de testes que você já fez, nos bancos indicados vc chegou a gerar em produção para algum cliente?

**Comment by lukBarros** [comment]
De qualquer forma estou a rodar mesmo no docker pra aproveitar seu empacotamento

**Comment by cas1260** [comment]
Ele usa algum framework? tentei rodar o que esta na pasta www porem não conseguir.
