### ISSUE TITLE
Running the project 

### ISSUE THREAD

**Issue by ghost** [jersobh/php-boleto-cnab#9]
Which file is used to run the project, I've tried the index.php file, but it is not working.

**Comment by jersobh** [comment]
It runs with docker. 

$ cd php-boleto-cnab  
$ docker-compose up  
$ cd www/api  
$ composer update

**Comment by ghost** [comment]
Is there some kind of web interface to launch in the browser.

**Comment by jersobh** [comment]
It's a rest API, not a web platform. The only html thing you should see is the welcome screen at localhost.
